variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress

image: docker:20.10.24
services:
  - docker:20.10.24-dind

cache:
  paths:
    - .m2/repository

before_script:
  - docker info

stages:
  - test
  - deploy

.deploy-app:
  stage: deploy
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS test'

deploy-app:sba-2.4:
  extends:
    - .deploy-app
