version: "3.3"

services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    restart: "always"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  spring-boot-admin-2.4:
    image: "stekoe/spring-boot-admin:2.4.4"
    restart: "always"
    ports:
      - "8888:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sba-2-4.rule=PathPrefix(`/sba/2.4`)"
      - "traefik.http.routers.sba-2-4.entrypoints=web"
    environment:
      - server.servlet.context-path=/sba/2.4

  spring-boot-admin-2.5:
    image: "stekoe/spring-boot-admin:2.5.5"
    restart: "always"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sba-2-5.rule=PathPrefix(`/sba/2.5`)"
      - "traefik.http.routers.sba-2-5.entrypoints=web"
    environment:
      - server.servlet.context-path=/sba/2.5

  spring-boot-admin-2.6:
    image: "stekoe/spring-boot-admin:2.6.4"
    restart: "always"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sba-2-6.rule=PathPrefix(`/sba/2.6`)"
      - "traefik.http.routers.sba-2-6.entrypoints=web"
    environment:
      - server.servlet.context-path=/sba/2.6

